### ISSUE TITLE
Trouble using AppBus, pulled from NuGet

### ISSUE THREAD

**Issue by suitcasenuke** [darrencauthon/MvcTurbine.AppBus#1]
Hello, I pulled a copy of AppBus from NuGet, and I'm trying to use it in a manor similar to what Darren demoed at Nebraska Code Camp. As soon as I add the reference I get the following error running my MVC app

MVC Turbine could not find & load the dependencies for assembly 'MvcTurbine.AppBus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
## Dependencies that failed to load: 

Method 'Create' in type 'MvcTurbine.AppBus.Helpers.ServiceLocatorMessageHandlerFactory' from assembly 'MvcTurbine.AppBus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

---

Are there any demos out there that might be able to hold my hand through this first time AppBus setup? The MVC Music Store Turbine app seems to be using a different version of AppBus than what I'm pulling from NuGet, could that be the issue?

Thanks for your help

**Comment by darrencauthon** [comment]
Hello,

You are correct, the MVC Music Store example from my presentation was using a different version of MvcTurbine.AppBus.  The difference was that I compiled it against MVC Turbine V3, which was "officially" released just a day or two before my presentation (and I already had everything prepared at the time).

I do have an item on my todo list to update all of my MvcTurbine packages to V3.  That will resolve the issues with people switching over to V3.  It's been a busy week, but I will have time this weekend to finish it up.

I'm sorry for any trouble!  Let me know if you have any other questions.

Darren

**Comment by suitcasenuke** [comment]
Awesome response time! Thanks for the heads up, on what's going on.

**Comment by kapopken** [comment]
Sorry to bug, but did the new version ever get uploaded?

**Comment by darrencauthon** [comment]
No, not yet, but it will... it's on my pending item list, but I keep hitting postpone due to other things.  

It's the first thing I'll do tonight, promise. :)

**Comment by kapopken** [comment]
Thanks and like the guy above very nice response time!

**Comment by darrencauthon** [comment]
Ok, it's done! :)

I also took the opportunity to upgrade all of the MvcTurbine plugins.  This means that in addition to MvcTurbine.AppBus, you can also try MvcTurbine.GoogleSiteMap, MvcTurbine.MembershipProvider, and MvcTurbine.FluentValidation.  I tested each, and they all work.

I'll mark this issue as closed now.  Let me know if you have any other issues or questions.
