### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by suitcasenuke** [darrencauthon/MvcTurbine.AppBus#2]
I grabbed the latest version of MvcTurbine.AppBus and have a few questions. 

1) When creating a class that handles my raised event, I implement IMessageHandler, is that IMessageHandler the interface that is in the other AppBus project you have up on github? If so is the version up here older than the one MvcTurbine.AppBus is complied with? I ask because it looks like we need to implement a CanHandle method, but when I pull AppBus from git, I don't see that in the interface.

2) Where do I want to call the .Add method on app bus? I'm guessing somewhere in the global.asax but I'm not sure where, and if it is in the global.asax, where do I get the ApplicationBus object to call the add on?

Thanks

**Comment by darrencauthon** [comment]
I looked, and sure enough -- I have ZERO documentation on this.  I thought I had gone through all of my old apps and added at least some basic explanation of what was going on, but I really dropped the ball on this one.

So my apologizes!  I'm going to write up a quick explanation for you here, and soon I'll write this up formally in the wiki.  So here I go:

Step 1:  Set up your MVC Turbine project.

Step 2:  Install MvcTurbine.AppBus through Nuget.

Step 3:  Add a test message and a couple test message handlers like below (you can just copy-paste this code _anywhere_ in your application).

```
public class TestMessage : IEventMessage
{
    public string LogThis { get; set; }
}

public class FirstTestMessageHandler : IMessageHandler<TestMessage>
{
    public void Handle(TestMessage message)
    {
        // do something here
    }
}

public class SecondTestMessageHandler : IMessageHandler<TestMessage>
{
    public void Handle(TestMessage message)
    {
        // do something else here
    }
}
```

Step 4:  Somewhere in your application where you want to publish a message, add a constructor dependency on "IApplicationBus".  Here's a sample HomeController that publishes when someone hits the home page:

```
public class HomeController : Controller
{
    private readonly IApplicationBus applicationBus;

    public HomeController(IApplicationBus applicationBus)
    {
        this.applicationBus = applicationBus;
    }

    public ActionResult Index()
    {
        applicationBus.Send(new TestMessage {LogThis = "Someone hit the home page"});

        ViewBag.Message = "Welcome to ASP.NET MVC!";

        return View();
    }
}
```

If you put some debugging lines in the message handlers, you'll notice that they each get instantiated and called one the message is published.  

It's really that easy.  That's part of the magic of MVC Turbine:  All of the details about how message handlers get to the messages, how it all works through IoC, etc. can be handled by me, the author, and then all you have to worry about is:  "What do I want to do with it?"

**Comment by darrencauthon** [comment]
Does that answer your questions for now?  If so, I'd like to close it... just to get the pending notification off the dashboard. :)

**Comment by suitcasenuke** [comment]
Indeed it does!! I was able to throw together a simple MVCTurbine site, and get AppBus working. I actually had code very close to what you listed, but I think I still had an old version of AppBus, from before NuGet was updated the other day, that was dealing me fits. Thanks for the help.
